apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    app: {{ include "flask-app.name" . }}
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: {{ include "flask-app.name" . }}
  type: LoadBalancer